"""add_class_image_to_

Revision ID: 0cdefd9f16ba
Revises: a8307a5e4d74
Create Date: 2026-04-03 09:19:57.951696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0cdefd9f16ba'
down_revision: Union[str, Sequence[str], None] = 'a8307a5e4d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom', sa.Column('class_image', sa.LargeBinary(), nullable=True))
    op.add_column('course', sa.Column('course_thumbnail', sa.LargeBinary(), nullable=True))
    op.add_column('lecture', sa.Column('lecture_image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture', 'lecture_image')
    op.drop_column('course', 'course_thumbnail')
    op.drop_column('classroom', 'class_image')
    # ### end Alembic commands ###
