"""add department model

Revision ID: 1dc3146bcc0f
Revises: 9920f375ac12
Create Date: 2026-04-16 14:15:17.127029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dc3146bcc0f'
down_revision: Union[str, Sequence[str], None] = '9920f375ac12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.add_column('classroom', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classroom', 'department', ['department_id'], ['department_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classroom', type_='foreignkey')
    op.drop_column('classroom', 'department_id')
    op.drop_table('department')
    # ### end Alembic commands ###
