"""change_image_to_string

Revision ID: 5e2aafcd363e
Revises: 0cdefd9f16ba
Create Date: 2026-04-03 09:32:12.409280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e2aafcd363e'
down_revision: Union[str, Sequence[str], None] = '0cdefd9f16ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classroom', 'class_image',
               existing_type=postgresql.BYTEA(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('course', 'course_thumbnail',
               existing_type=postgresql.BYTEA(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('lecture', 'lecture_image',
               existing_type=postgresql.BYTEA(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lecture', 'lecture_image',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('course', 'course_thumbnail',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('classroom', 'class_image',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
