"""create donation table

Revision ID: 6bd343bb4acf
Revises: ed278ab7d1bc
Create Date: 2026-03-13 11:47:16.904890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6bd343bb4acf'
down_revision: Union[str, Sequence[str], None] = 'ed278ab7d1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('donation_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('provider_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_index(op.f('ix_donation_donation_id'), 'donation', ['donation_id'], unique=False)
    op.create_index(op.f('ix_donation_provider_transaction_id'), 'donation', ['provider_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donation_provider_transaction_id'), table_name='donation')
    op.drop_index(op.f('ix_donation_donation_id'), table_name='donation')
    op.drop_table('donation')
    # ### end Alembic commands ###
