"""add_cascade_delete

Revision ID: 86f72b15fdb9
Revises: 5e2aafcd363e
Create Date: 2026-04-03 11:54:42.303064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86f72b15fdb9'
down_revision: Union[str, Sequence[str], None] = '5e2aafcd363e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_mastery_course_id_fkey'), 'student_mastery', type_='foreignkey')
    op.create_foreign_key(None, 'student_mastery', 'course', ['course_id'], ['course_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_mastery', type_='foreignkey')
    op.create_foreign_key(op.f('student_mastery_course_id_fkey'), 'student_mastery', 'course', ['course_id'], ['course_id'])
    # ### end Alembic commands ###
