"""refactor_teacher_assignment_and_departments

Revision ID: 9382ccb198e3
Revises: 1dc3146bcc0f
Create Date: 2026-04-24 07:18:30.567152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9382ccb198e3'
down_revision: Union[str, Sequence[str], None] = '1dc3146bcc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_assignment', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_teacher_assignment_class_id'), table_name='teacher_assignment')
    op.create_index(op.f('ix_teacher_assignment_department_id'), 'teacher_assignment', ['department_id'], unique=False)
    op.drop_constraint(op.f('teacher_assignment_class_id_fkey'), 'teacher_assignment', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_assignment', 'department', ['department_id'], ['department_id'])
    op.drop_column('teacher_assignment', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_assignment', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teacher_assignment', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_assignment_class_id_fkey'), 'teacher_assignment', 'classroom', ['class_id'], ['class_id'])
    op.drop_index(op.f('ix_teacher_assignment_department_id'), table_name='teacher_assignment')
    op.create_index(op.f('ix_teacher_assignment_class_id'), 'teacher_assignment', ['class_id'], unique=False)
    op.drop_column('teacher_assignment', 'department_id')
    # ### end Alembic commands ###
