"""add_cascade_delete_to_user_relations

Revision ID: 9920f375ac12
Revises: 86f72b15fdb9
Create Date: 2026-04-07 20:27:40.104317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9920f375ac12'
down_revision: Union[str, Sequence[str], None] = '86f72b15fdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comment_user_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('donation_user_id_fkey'), 'donation', type_='foreignkey')
    op.create_foreign_key(None, 'donation', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('enrollment_student_id_fkey'), 'enrollment', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment', 'user', ['student_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('profile_user_id_fkey'), 'profile', type_='foreignkey')
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quiz_attempt_student_id_fkey'), 'quiz_attempt', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempt', 'user', ['student_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_mastery_user_id_fkey'), 'student_mastery', type_='foreignkey')
    op.create_foreign_key(None, 'student_mastery', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_mastery', type_='foreignkey')
    op.create_foreign_key(op.f('student_mastery_user_id_fkey'), 'student_mastery', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'quiz_attempt', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempt_student_id_fkey'), 'quiz_attempt', 'user', ['student_id'], ['user_id'])
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.create_foreign_key(op.f('profile_user_id_fkey'), 'profile', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.create_foreign_key(op.f('enrollment_student_id_fkey'), 'enrollment', 'user', ['student_id'], ['user_id'])
    op.drop_constraint(None, 'donation', type_='foreignkey')
    op.create_foreign_key(op.f('donation_user_id_fkey'), 'donation', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_user_id_fkey'), 'comment', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
