"""First Migration

Revision ID: b3dda0bbaf65
Revises: 
Create Date: 2026-03-04 15:36:01.577518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3dda0bbaf65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'class_manager', 'user', ['manager_id'], ['user_id'])
    op.create_foreign_key(None, 'course', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'enrollment', 'user', ['student_id'], ['user_id'])
    op.create_foreign_key(None, 'lecture', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'quiz', 'lecture', ['lecture_id'], ['lecture_id'])
    op.create_foreign_key(None, 'quiz', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'quiz_attempt', 'question_option', ['answer_id'], ['option_id'])
    op.create_foreign_key(None, 'quiz_attempt', 'user', ['student_id'], ['user_id'])
    op.create_foreign_key(None, 'student_mastery', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'teacher_assignment', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'user_permission', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permission', type_='foreignkey')
    op.drop_constraint(None, 'teacher_assignment', type_='foreignkey')
    op.drop_constraint(None, 'student_mastery', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempt', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempt', type_='foreignkey')
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.drop_constraint(None, 'lecture', type_='foreignkey')
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'class_manager', type_='foreignkey')
    # ### end Alembic commands ###
