name: Backend Dockerized Tests

on:
  push:
    branches: [ main, dev ]
    paths:
      - backend/**
      - tests/**

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_FROM: ${{ secrets.MAIL_FROM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      REFRESH_TOKEN_EXPIRE_DAYS: ${{ secrets.REFRESH_TOKEN_EXPIRE_DAYS }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      BACKEND_CORS_ORIGINS: ${{ secrets.BACKEND_CORS_ORIGINS }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      POSTGRES_USER: postgres
      POSTGRES_DB: lms
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Start Services
        run: |
          docker compose up --build -d db backend
          sleep 20

      - name: Debug containers
        run: |
          docker compose ps
          docker compose logs backend
          docker compose logs db

      - name: Run Pytest inside Container
        run: |
          docker compose exec -T backend uv run pytest /app/tests -v
        env:
          SQLALCHEMY_DATABASE_URI: ${{ secrets.DATABASE_URL }}
          PYTHONPATH: .